# Generated by Django 5.2.5 on 2026-01-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('month', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('day', models.PositiveIntegerField()),
                ('escopo', models.CharField(choices=[('Nacional', 'Nacional'), ('Estadual', 'Estadual'), ('Municipal', 'Municipal')], default='Nacional', max_length=20)),
            ],
        ),
    ]
