# Generated by Django 6.0.1 on 2026-03-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feriadou', '0003_solicitacao'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feriado',
            index=models.Index(fields=['month', 'escopo', 'estado'], name='feriadou_fe_month_d0bdb8_idx'),
        ),
    ]
